trigger: none

pool: Default

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

- task: PowerShell@2
  displayName: 'npm install'
  inputs:
    targetType: 'inline'
    script: 'npm install'

- task: PowerShell@2
  displayName: 'NPM Run Build'
  inputs:
    targetType: 'inline'
    script: 'npm run build'
